kind: pipeline
type: docker
name: build

steps:  
  - name: validate_sh_config
    image: python:3.11
    commands:
      - pip3 install -r tests/config_validation/requirements.txt
      - python3 tests/config_validation/validate.py
    when:
      branch:
        - master

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CHAT_ID
    when:
      status: [ failure ]
